name: mapbox_draw_polygon_area
description: A Flutter package that allows you to calculate the area of a polygon drawn on a Mapbox map.
version: 0.0.9
homepage: https://github.com/BadalAc/Mapbox_draw_polygon_area.git
publish_to: none
environment:
  sdk: '>=2.18.5 <3.0.0'
  flutter: ">=1.17.0"



dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
 
  
  
  get: ^4.6.1
  maps_toolkit: ^2.0.0
  snapping_sheet: ^3.1.0
  flutter_plugin_android_lifecycle: ^2.0.7
  mapbox_gl_modified:
    git:
      url: https://github.com/khaledHelmy-Dev/mapbox_gl_modified_asset.git
      ref: master


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  
  
  
dependency_overrides:
  
 

examples:
  - example/mapbox_draw_example/example.md:
     

# The following section is specific to Flutter packages.
flutter:

  # To add assets to your package, add an assets section, like this:
  assets:
    - assets/icon/
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
